spring:
 thymeleaf:
  cache: false

 datasource:
  url: jdbc:mysql://127.0.0.1:3500/ecommerce
  username: root
  password: wjd0322189
  driver-class-name: com.mysql.cj.jdbc.Driver

 jpa:
  hibernate:
   ddl-auto: none
  properties:
   hibernate:
    format_sql: true
    show_sql: true
    default_batch_fetch_size: 100
    use_sql_comments: true
  open-in-view: false

  devtools:
   livereload:
    enabled: true
  thymeleaf:
   cache: false

logging:
 level:
  root: info

server:
 port: 9999

#apis:
# product-graphql-api:
#  url: http://localhost:8083/graphql
# order-api:
#  url: http://localhost:9090/providers/order-api/v1/orders
